services:
  - type: web
    name: naijaspend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    autoDeploy: true
    plan: free
