import { Router } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { db } from '../db.js';
import { auth, wrap, bad, verifyToken } from '../util.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const UPLOADS_DIR = path.join(__dirname, '..', 'data', 'uploads');
fs.mkdirSync(UPLOADS_DIR, { recursive: true });

const MIME = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp' };
const MAX_BYTES = 1.5 * 1024 * 1024;

export function removeReceiptFile(tx) {
  if (!tx?.receipt) return;
  // filename is generated by us only — no path traversal risk
  const safe = path.basename(String(tx.receipt));
  fs.promises.unlink(path.join(UPLOADS_DIR, safe)).catch(() => { });
}

export function saveReceiptDataUrl(txId, dataUrl) {
  const m = String(dataUrl || '').match(/^data:image\/(jpeg|jpg|png|webp);base64,(.+)$/);
  if (!m) throw Object.assign(new Error('Only JPEG, PNG or WebP images are supported.'), { status: 400 });
  const buf = Buffer.from(m[2], 'base64');
  if (!buf.length) throw Object.assign(new Error('The image looks empty.'), { status: 400 });
  if (buf.length > MAX_BYTES) throw Object.assign(new Error('Image too large — keep receipts under 1.5 MB.'), { status: 400 });
  const ext = m[1] === 'jpeg' ? 'jpg' : m[1];
  const name = `tx${txId}-${crypto.randomBytes(4).toString('hex')}.${ext}`;
  fs.writeFileSync(path.join(UPLOADS_DIR, name), buf);
  return name;
}

const router = Router();

// serves the stored receipt image; accepts the JWT via header or ?token= (for <img> tags)
router.get('/:txId', wrap((req, res) => {
  const qToken = String(req.query.token || '');
  const header = req.headers.authorization || '';
  const token = header.startsWith('Bearer ') ? header.slice(7) : qToken;
  const payload = verifyToken(token);
  if (!payload) return bad(res, 'Not authenticated', 401);
  const userId = payload.sub;

  const tx = db.prepare('SELECT id, receipt FROM transactions WHERE id = ? AND user_id = ?').get(Number(req.params.txId), userId);
  if (!tx?.receipt) return bad(res, 'Receipt not found.', 404);
  const safe = path.basename(String(tx.receipt));
  const file = path.join(UPLOADS_DIR, safe);
  if (!fs.existsSync(file)) return bad(res, 'Receipt file is missing.', 404);
  const ext = path.extname(safe).slice(1).toLowerCase();
  res.setHeader('Content-Type', MIME[ext] || 'application/octet-stream');
  res.setHeader('Cache-Control', 'private, max-age=3600');
  res.send(fs.readFileSync(file));
}));

export default router;
